services:
  auth-service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "8000:8000"

  notes-service:
    build: ./notes_service
    container_name: notes_service
    depends_on:
      - auth-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - notes-service
